# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
      - Area-Build & Infrastructure
      - External
  categories:
    - title: Breaking Changes 🧨
      labels:
        - breaking change
    - title: Exciting New Features 🎉
      labels:
        - enhancement
        - new feature
    - title: Bug fixes🛠️
      labels:
        - bug
    - title: Area-Accessibility
      labels:
        - Area-Accessibility
    - title: Area-Automation
      labels:
        - Area-Automation
    - title: Area-Auth
      labels:
        - Area-Auth
    - title: Area-API
      labels:
        - Area-API
    - title: Area-C#
      labels:
        - Area-C#
    - title: Area-Documentation
      labels:
        - Area-Documentation
    - title: Area-F#
      labels:
        - Area-F#
    - title: Area-Formatting
      labels:
        - Area-Formatting
    - title: Area-HTTP
      labels:
        - Area-HTTP (HttpKernel, Visual Studio HTTP Editor)
    - title: Area-JavaScript HTML CSS
      labels:
        - Area-JavaScript HTML CSS
    - title: Area-Jupyter
      labels:
        - Area-Jupyter
    - title: Area-Jupyter subkernels
      labels:
        - Area-Jupyter subkernels (Python, R, Julia, etc.)
    - title: Area-Language Services
      labels:
        - Area-Language Services
    - title: Area-Localization and Globalization
      labels:
        - Area-Localization and Globalization
    - title: Area-Messaging, Comms, and Scheduling
      labels:
        - Area-Messaging and Comms
        - Area-Messaging / scheduling / comms
    - title: Area-Packages and Extensions
      labels:
        - Area-Packages and Extensions
    - title: Area-Performance
      labels:
        - Area-Performance
    - title: Area-Polyglot Notebooks Extension
      labels:
        - Area-Polyglot Notebooks Extension
    - title: Area-PowerShell
      labels:
        - Area-PowerShell
    - title: Area-Python
      labels:
        - Area-Python
    - title: Area-SQL / data querying
      labels:
        - Area-SQL / data querying
    - title: Area-Variable sharing
      labels:
        - Area-Variable sharing
    - title: Area-Visualization
      labels:
        - Area-Visualization
    - title: Area-VisualStudio
      labels:
        - Area-VisualStudio
    - title: Other Changes
      labels:
        - "*"
