# CI and PR triggers
trigger:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - '*'
    exclude:
    - '**/*.md'
    - .config/*
    - .devcontainer/*
    - .github/*
    - .vscode/*
    - assets/*
    - docs/*
    - images/*
    - .editorconfig
    - .gitignore
    - '*.txt'
    - '*.github-issues'

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - '*'
    exclude:
    - '**/*.md'
    - .config/*
    - .devcontainer/*
    - .github/*
    - .vscode/*
    - assets/*
    - docs/*
    - images/*
    - .editorconfig
    - .gitignore
    - '*.txt'
    - '*.github-issues'

# Scheduled trigger that will run at 8:00 AM every Monday and Wednesday
schedules:
- cron: "0 8 * * Mon"
  displayName: Weekly build for Localization Updates (Monday)
  branches:
    include:
    - main
- cron: "0 8 * * Wed"
  displayName: Weekly build for Localization Updates (Wednesday)
  branches:
    include:
    - main

# Variables
variables:
<<<<<<< HEAD
- template: /eng/templates/variables-template.yml@self
- template: /eng/common/templates/variables/pool-providers.yml@self

=======
  - name: _TeamName
    value: DotNetInteractive
  - name: _BuildConfig
    value: Release
  - name: _PublishUsingPipelines
    value: true
  - name: _DotNetArtifactsCategory
    value: .NETCore
  - name: DisableDockerDetector
    value: true
  - name: NodeJSVersion
    value: '16.13.0'
  - name: LocPRCreationEnabled
    value: ${{ eq(variables['Build.Reason'], 'Schedule') }}
  - name: Codeql.Enabled
    value: true
  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    - name: _DotNetValidationArtifactsCategory
      value: .NETCoreValidation
    - group: DotNet-Interactive-SDLValidation-Params
  - template: /eng/common/templates/variables/pool-providers.yml
>>>>>>> b7307f61 (Jupyter test flakiness fixes (#3834))

stages:
- stage: build
  displayName: Build and Test
  jobs:
  - ${{ if ne(variables['System.TeamProject'], 'public') }}:
    - template: /eng/common/templates/job/onelocbuild.yml
      parameters:
        MirrorRepo: interactive
        MirrorBranch: main
        SkipLocProjectJsonGeneration: true
        LclSource: lclFilesfromPackage
        LclPackageId: 'LCL-JUNO-PROD-INTERACTIVE'
        CreatePr: $(LocPRCreationEnabled)

  - template: /eng/common/templates/jobs/jobs.yml
    parameters:
      enableMicrobuild: true
      enablePublishBuildArtifacts: true
      enablePublishTestResults: true
      enablePublishBuildAssets: true
      enablePublishUsingPipelines: $(_PublishUsingPipelines)

      jobs:
      - job: Windows_NT
        pool:
          ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
            name: $(DncEngPublicBuildPool)
            demands: ImageOverride -equals windows.vs2022.amd64.open
          ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
            name: $(DncEngInternalBuildPool)
            demands: ImageOverride -equals windows.vs2022.amd64
        timeoutInMinutes: 200
        variables:
        # Enable signing for internal, non-PR builds
        - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
          - group: DotNet-Symbol-Server-Pats
          - name: _SignType
            value: Real
          - name: _BuildArgs
            value: /p:SignType=$(_SignType)
                   /p:DotNetSignType=$(_SignType)
                   /p:MicroBuild_SigningEnabled=true
                   /p:TeamName=$(_TeamName)
                   /p:DotNetPublishUsingPipelines=$(_PublishUsingPipelines)
                   /p:DotNetArtifactsCategory=$(_DotNetArtifactsCategory)
                   /p:DotNetSymbolServerTokenMsdl=$(microsoft-symbol-server-pat)
                   /p:DotNetSymbolServerTokenSymWeb=$(symweb-symbol-server-pat)
                   /p:OfficialBuildId=$(BUILD.BUILDNUMBER)
                   /p:PublishToSymbolServer=true
        # else
        - ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
          - name: _SignType
            value: Test
          - name: _BuildArgs
            value: /p:SignType=$(_SignType)

        steps:
        - checkout: self
          clean: true

<<<<<<< HEAD
        # Use common task group
        - template: /eng/templates/build-and-test-tasks.yml@self
          parameters:
            platform: windows
        
=======
        # Azure DevOps doesn't support git symlinks on Windows so we have to fake it
        - pwsh: . "$(Build.SourcesDirectory)\src\ensure-symlinks.ps1"
          displayName: ensure symlinks

        - task: NodeTool@0
          displayName: Add NodeJS/npm
          inputs:
            versionSpec: $(NodeJSVersion)

        # - task: UseDotNet@2
        #   displayName: Use .NET SDK
        #   inputs:
        #     packageType: sdk
        #     useGlobalJson: true
        #     includePreviewVersions: true
        #     workingDirectory: $(Build.SourcesDirectory)
        #     installationPath: $(Agent.ToolsDirectory)/dotnet

        - script: |
            robocopy "eng\resources" "$(Build.SourcesDirectory)\artifacts"
            :: robocopy return codes are terrible; 1 means files were copied
            if "%errorlevel%" == "1" exit /b 0
            exit /b 1
          displayName: Prevent test directory crawling

        - pwsh: |
            $testArg = if ($env:SKIPTESTS -ne "true") { "-test" } else { "" }
            Write-Host "##vso[task.setvariable variable=_TestArgs]$testArg"
          displayName: Promote variables

        - script: eng\CIBuild.cmd
            -configuration $(_BuildConfig)
            -prepareMachine
            -sign
            $(_BuildArgs)
            $(_TestArgs)
          displayName: Build
          env:
            POCKETLOGGER_LOG_PATH: $(Build.SourcesDirectory)\artifacts\TestResults\$(_BuildConfig)\pocketlogger.test.log
            DOTNET_INTERACTIVE_FRONTEND_NAME: CI

        - pwsh: ./test-retry-runner.ps1 -buildConfig $env:BUILDCONFIG
          displayName: Test / Blame
          workingDirectory: $(Build.SourcesDirectory)
          env:
            BUILDCONFIG: $(_BuildConfig)
            POCKETLOGGER_LOG_PATH: $(Build.SourcesDirectory)\artifacts\TestResults\$(_BuildConfig)\pocketlogger.test.log
          condition: ne(variables['SkipTests'], 'true')

>>>>>>> b7307f61 (Jupyter test flakiness fixes (#3834))
        - task: PublishBuildArtifacts@1
          displayName: Publish Test results and Blame dumps
          inputs:
            pathToPublish: $(Build.SourcesDirectory)/artifacts/TestResults/$(_BuildConfig)
            artifactName: Windows_test_results_and_dumps
            artifactType: container
          condition: always()

<<<<<<< HEAD
=======
        # publish VS Code and npm test results
        - task: PublishTestResults@2
          displayName: Publish VS Code extension and npm test results
          inputs:
            testResultsFormat: VSTest
            testResultsFiles: '**/*.*'
            searchFolder: '$(Build.SourcesDirectory)/artifacts/TestResults'
          condition: always()

        # pack and publish vscode and npm
        - task: PowerShell@2
          displayName: Pack VS Code Extensions
          inputs:
            filePath: $(Build.SourcesDirectory)/eng/package/PackVSCodeExtension.ps1
            arguments: -stableToolVersionNumber $(StableToolVersionNumber) -outDir "$(Build.ArtifactStagingDirectory)\vscode"
            workingDirectory: "$(Build.SourcesDirectory)/src"
            pwsh: true

>>>>>>> b7307f61 (Jupyter test flakiness fixes (#3834))
        - task: PublishBuildArtifacts@1
          displayName: Publish VSCode extension artifacts
          inputs:
            pathToPublish: $(Build.ArtifactStagingDirectory)\vscode
            artifactName: vscode
            artifactType: container

        - task: PublishBuildArtifacts@1
          displayName: Publish NPM package artifacts
          inputs:
            pathToPublish: $(Build.ArtifactStagingDirectory)\npm
            artifactName: npm
            artifactType: container

        - task: PublishBuildArtifacts@1
          displayName: Publish packages to artifacts container
          inputs:
            pathToPublish: $(Build.SourcesDirectory)\artifacts\packages\$(_BuildConfig)
            artifactName: packages
            artifactType: container


  - template: /eng/common/templates/jobs/jobs.yml
    parameters:
      enableMicrobuild: true
      enablePublishBuildArtifacts: true
      enablePublishTestResults: true
      enablePublishBuildAssets: false
      enablePublishUsingPipelines: false
      jobs:
      - job: Linux
        pool:
          ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
            name: $(DncEngPublicBuildPool)
            demands: ImageOverride -equals Build.Ubuntu.1804.Amd64.Open
          ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
            name: $(DncEngInternalBuildPool)
            demands: ImageOverride -equals Build.Ubuntu.1804.Amd64
        timeoutInMinutes: 200
        variables:
        # Enable signing for internal, non-PR builds
        - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
          - name: _SignType
            value: Test
          - name: _BuildArgs
            value: /p:SignType=$(_SignType)
              /p:DotNetSignType=$(_SignType)
              /p:TeamName=$(_TeamName)
              /p:OfficialBuildId=$(BUILD.BUILDNUMBER)
        # else
        - ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
          - name: _SignType
            value: Test
          - name: _BuildArgs
            value: /p:SignType=$(_SignType)

        steps:
        - checkout: self
          clean: true

<<<<<<< HEAD
        # Use common task group
        - template: /eng/templates/build-and-test-tasks.yml@self
          parameters:
            platform: linux
        
=======
        - task: NodeTool@0
          displayName: Add NodeJS/npm
          inputs:
            versionSpec: $(NodeJSVersion)

        # - task: UseDotNet@2
        #   displayName: Use .NET SDK
        #   inputs:
        #     packageType: sdk
        #     useGlobalJson: true
        #     includePreviewVersions: true
        #     workingDirectory: $(Build.SourcesDirectory)
        #     installationPath: $(Agent.ToolsDirectory)/dotnet

        - script: |
            mkdir -p "$(Build.SourcesDirectory)/artifacts"
            rm -rf "$(Build.SourcesDirectory)/artifacts/*"
            cp eng/resources/* "$(Build.SourcesDirectory)/artifacts"
          displayName: Prevent test directory crawling

        - pwsh: |
            $testArg = if ($env:SKIPTESTS -ne "true") { "--test" } else { "" }
            Write-Host "##vso[task.setvariable variable=_TestArgs]$testArg"
          displayName: Promote variables

        - script: ./eng/cibuild.sh
            --configuration $(_BuildConfig)
            --prepareMachine
            $(_TestArgs)
          displayName: Build
          env:
            POCKETLOGGER_LOG_PATH: $(Build.SourcesDirectory)/artifacts/TestResults/$(_BuildConfig)/pocketlogger.test.log
            DOTNET_INTERACTIVE_FRONTEND_NAME: CI

        - pwsh: ./test-retry-runner.ps1 -buildConfig $env:BUILDCONFIG
          displayName: Test / Blame
          workingDirectory: $(Build.SourcesDirectory)
          env:
            BUILDCONFIG: $(_BuildConfig)
            POCKETLOGGER_LOG_PATH: $(Build.SourcesDirectory)/artifacts/TestResults/$(_BuildConfig)/pocketlogger.test.log
          condition: ne(variables['SkipTests'], 'true')

>>>>>>> b7307f61 (Jupyter test flakiness fixes (#3834))
        - task: PublishBuildArtifacts@1
          displayName: Publish Test results and Blame dumps
          inputs:
            pathToPublish: $(Build.SourcesDirectory)/artifacts/TestResults/$(_BuildConfig)
            artifactName: Linux_test_results_and_dumps
            artifactType: container
          condition: always()

<<<<<<< HEAD
=======
        # publish VS Code and npm test results
        - task: PublishTestResults@2
          displayName: Publish VS Code extension and npm test results
          inputs:
            testResultsFormat: VSTest
            testResultsFiles: '**/*.*'
            searchFolder: '$(Build.SourcesDirectory)/artifacts/TestResults'
          condition: always()

>>>>>>> b7307f61 (Jupyter test flakiness fixes (#3834))
#---------------------------------------------------------------------------------------------------------------------#
#                                                    Post Build                                                       #
#---------------------------------------------------------------------------------------------------------------------#
  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    - template: /eng/templates/post-build-tasks.yml@self

#---------------------------------------------------------------------------------------------------------------------#
#                                                    NPM Publish                                                      #
#---------------------------------------------------------------------------------------------------------------------#
  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    - template: /eng/templates/npm-publish-tasks.yml@self
